name: Git Action Based Mule Deployment

on:
  push:
    branches:
      - 'main'

jobs:
  deployJar:
    name: Create App Jar and Deploy
    runs-on: ubuntu-18.04
    environment:
      name: Development
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Print Github Commit SHA Value
        run: echo ${{ github.sha }}
      #- name: Maven Package
      #  run: mvn -B -U -e -V clean -DskipTests package
      #- name: Maven MUnit
      #  run: mvn -X clean test
      #- name: Maven Deploy
      #  run: mvn -U -V -e -B -DskipTests deploy -DmuleDeploy -Dmule.version="4.3.0" -Danypoint.username="${{ secrets.DEV_USER }}" -Danypoint.password="${{ #secrets.DEV_PASSWORD }}" -Dcloudhub.app="helloworld-rk173346" -Dcloudhub.environment="Sandbox" -Dcloudhub.bg="BDR-Engineering" -Dcloudhub.worker="Micro"
      #- name: Send email post job completion
      #  uses: dawidd6/action-send-mail@v3
      #  with:
      #   server_address: smtp.gmail.com
      #    server_port: 465
      #    username: ${{secrets.MAIL_USERNAME}}
      #    password: ${{secrets.MAIL_PASSWORD}}
      #    subject: Workflow finished
      #    to: rajat.kumar1@apisero.com
      #    from: rk173346@gmail.com
      #    body: Job completed ${{job.status}}
          # Optional HTML body read from file:
          #html_body: file://README.html
          # Optional carbon copy recipients:
          #cc: kyloren@example.com,leia@example.com
          # Optional attachments:
          #attachments: attachments.zip,git.diff,./dist/static/main.js
